Lint/DebugCalls:
  Description: Disallows debug-related calls
  Excluded:
  - samples/*
  Enabled: true
  Severity: Warning

Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
  - src/bplist/parser.cr
  Enabled: true
  Severity: Warning
